# Generated by Django 5.0.1 on 2024-01-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rank', models.FloatField()),
                ('country_or_region', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('gdp_per_capita', models.FloatField()),
                ('social_support', models.FloatField()),
                ('healthy_life_expectancy', models.FloatField()),
                ('freedom_to_make_life_choices', models.FloatField()),
                ('generosity', models.FloatField()),
                ('perceptions_of_corruption', models.FloatField()),
                ('cost_of_living_index', models.FloatField()),
                ('rent_index', models.FloatField()),
                ('cost_of_living_plus_rent_index', models.FloatField()),
                ('groceries_index', models.FloatField()),
                ('restaurant_price_index', models.FloatField()),
                ('local_purchasing_power_index', models.FloatField()),
            ],
        ),
    ]
