# Generated by Django 5.0.1 on 2024-01-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countrydata',
            old_name='overall_rank',
            new_name='composite_score',
        ),
        migrations.AddField(
            model_name='countrydata',
            name='final_rank',
            field=models.FloatField(default=40),
            preserve_default=False,
        ),
    ]
