# Generated by Django 5.0.1 on 2024-01-13 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_project', '0002_rename_overall_rank_countrydata_composite_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrydata',
            name='composite_score',
        ),
        migrations.RemoveField(
            model_name='countrydata',
            name='final_rank',
        ),
    ]
